### ISSUE TITLE
Error: Wrong .match() argument

### ISSUE THREAD

**Issue by voischev** [gulp-bem/gulp-bem-xjst#1]
В собранном бандле для bemhtml или bemtree одна и та же ошибка.

```
node -p "require('./build/bundles/index/index.bemhtml.js').apply({});"
/Users/voischev/projects/bem-full-stack/build/bundles/index/index.bemhtml.js:1869
    throw new Error(msg || 'Assertion failed');
    ^

Error: Wrong .match() argument
    at assert (/Users/voischev/projects/bem-full-stack/build/bundles/index/index.bemhtml.js:1869:11)
    at Tree.match (/Users/voischev/projects/bem-full-stack/build/bundles/index/index.bemhtml.js:1654:5)
    at Object.<anonymous> (/Users/voischev/projects/bem-full-stack/build/bundles/index/index.bemhtml.js:2181:1)
    at Tree.build (/Users/voischev/projects/bem-full-stack/build/bundles/index/index.bemhtml.js:1558:13)
    at BEMHTML.compile (/Users/voischev/projects/bem-full-stack/build/bundles/index/index.bemhtml.js:719:18)
    at Object.<anonymous> (/Users/voischev/projects/bem-full-stack/build/bundles/index/index.bemhtml.js:1890:5)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

Можно попробовать на проекте в этой ветке https://github.com/voischev/bem-full-stack/tree/gulp Коммит 34921dd5a57f8c7f5921b6b0a2ef8942d302a96b

**Comment by voischev** [comment]
слева сборка из enb, `"enb-bemxjst": "^4.1.0",`
справа из gulp `"gulp-bem-xjst": "^1.0.0",`

Наблюдаю обетрочку слева...

<img width="1432" alt="screen shot 2016-03-01 at 15 20 54" src="https://cloud.githubusercontent.com/assets/1510217/13426807/0128edba-dfc1-11e5-8ce2-9c71b6688dcb.png">

**Comment by qfox** [comment]
Нужно отфильтровать i-bem.bemhtml.js из bem-core
https://github.com/bem/project-stub/blob/feature/gulp/gulpfile.js#L50-L55

**Comment by qfox** [comment]
Закрываю, потому что проблема не в пакете и не может быть решена здесь.

**Comment by voischev** [comment]
:+1:
